### ISSUE TITLE
Feature: theme template file to be used by the plugin

### ISSUE THREAD

**Issue by pshemek** [lukasjuhas/lj-maintenance-mode#1]
It would be great to be able to put own template file to be used by Maintenance Mode.
The plugin seems to be simple and developer friendly so such enhancement would provide a lot of flexibility.

**Comment by lukasjuhas** [comment]
Hi macemmek,

Thank you for your feedback. This feature is currently on my TODO list and I hoping to get to this in the following weeks. I'm preparing 2.0 version with lot's of new features; but of course keeping it as simple as possible and without any "rubbish".

**Comment by pshemek** [comment]
Thanks for a quick response and good luck with further development!

**Comment by lukasjuhas** [comment]
Hey everyone, Hi @macemmek 

Due to high popularity of the plugin in the stage that it currently is in, I've decided that all such functionality like this will be featured in advanced version of the plugin which is currently in development. With this, I'll be closing this issue. Thank you!
