### ISSUE TITLE
Jetpack share still displays on pages in maintenance mode

### ISSUE THREAD

**Issue by manningg1972** [lukasjuhas/lj-maintenance-mode#15]
At the URL below you will see that with maintenance mode enabled, Jetpack share option still displays. 

http://530.67b.myftpupload.com/news/what-to-pack.php

**Comment by lukasjuhas** [comment]
Hi There,

Thank you for your feedback, I'll look in to this and release an update as soon as I'll patch it.

Lukas

**Comment by gablau** [comment]
I think the problem is the line 269:
`$content = apply_filters('the_content', $content);`
change the priority to 20 or more (default 10) so that the filter is executed last
`$content = apply_filters('the_content', $content, 20);`

**Comment by manningg1972** [comment]
Sorry that didn't do it. Tried 20 and higher, up to 99 and Jetpack sharing still shows. I have disabled Jetpack sharing for now on my staging server. If you come up with another possible solution I am happy to enable it and test it again.

**Comment by lukasjuhas** [comment]
Hi guys, 

Sorry I didn't have chance to look in to this yet, I was away. I will have a look this week.

Thanks!

**Comment by lukasjuhas** [comment]
@manningg1972 @gablau 

Hi guys, I have fixes this issue now - I haven't tested it properly so please if you have any further problems let me know.

Thanks!
