### ISSUE TITLE
roles table prefix

### ISSUE THREAD

**Issue by gablau** [lukasjuhas/lj-maintenance-mode#18]
Hi, 
with new version 2.0 of your great plugins, the function  `get_option( 'wp_user_roles' );`
not work on website that change te default $table_prefix to the wp-config.php file like:
`$table_prefix  = 'newprefix_';`

so the correct option name is: `get_option( 'newprefix_user_roles' )`

I think should be something like this:

```
global $wpdb;
get_option($wpdb->prefix.'user_roles');
```

Best regards

**Comment by lukasjuhas** [comment]
Hi @gablau,

I'm just on this! Thanks a lot! I'm gonna put that in right away.

Lukas
