### ISSUE TITLE
Admin bar - remove on disable - Feature Request

### ISSUE THREAD

**Issue by jeffmcneill** [lukasjuhas/lj-maintenance-mode#19]
The menu item Admin bar takes up a lot of precious horizontal pixel space. 

"Maintenance Mode: Enabled"
"Maintenance Mode: Disabled"

Having this appear all the time even when the Disabled state is going to be nearly all the time doesn't make sense. Also the text is unnecessarily long.
- Feature request: either have the Admin bar item not displayed when Maintenance Mode is Disabled, OR have an option to have it or not in settings
- Feature request: change the text displayed in the Admin bar a lot shorter, such as: Maint:On / Maint:Off. Same meaning, less screen real estate.

**Comment by lukasjuhas** [comment]
Hey @jeffmcneill !

Thanks for your request, that's actually something I've been thinking about so I'm gonna definitely look in to this! Maybe not the setting - as I don't want to overcrowd it but possibly the label - and I was thinking the same - hide it if it's not enabled - but then I know that these kind of features cause lot of confusion - if something appears and disappears - believe it or not, many people find this very very confusing and they are complaining that it's broken!

Thank you, I'll look in to this soon!

Lukas

**Comment by gedeminas** [comment]
I agree that an option would be overcrowding, so just an idea with icons:
When off: https://developer.wordpress.org/resource/dashicons/#hammer
When on: https://developer.wordpress.org/resource/dashicons/#hammer Maintenance (and red background)

**Comment by lukasjuhas** [comment]
@gedeminas Yeah, hammer seems like quite sensible icon for this. 

Might go that route..

**Comment by lukasjuhas** [comment]
Hey guys,

Just to let you know, this will be included in 2.1 which will be released this week.

Thanks again.
