### ISSUE TITLE
Maintenance Mode: Disabled/Enabled

### ISSUE THREAD

**Issue by ghost** [lukasjuhas/lj-maintenance-mode#29]
Hello, 
I am using your Maintenance Mode and I like it.
Because it is very simple and useful.

I have a proposal and posted here. But it is not the issue.
On the top of the web page, current Maintenance Mode status is shown as Disabled or Enabled.
I sometimes confuse it as the site is Disabled or Enabled.
But it means the Maintenance Mode is Disabled or Enabled.
So I think if the message is, for example, Site Hidden or Site Shown, it is better. How about?

**Comment by lukasjuhas** [comment]
Hey @hiromi3,

Thank you for your suggestion,

I'm gonna think about this and see if there is something more sensible. I let you know once I make decision.

In the mean time any other suggestions re this are more than welcome.

Lukas

**Comment by ghost** [comment]
lukasjuhas,
Thank you for your reply.
I am looking forward to receiving the news from you!

**Comment by lukasjuhas** [comment]
Hey @hiromi3,

Sorry, I will not be changing this anytime soon, although what you can do is completely disable the indicator using this snippet:

```
add_filter( 'ljmm_admin_bar_indicator_enabled', '__return_false', 100 );
```

For now, the current indicator fits most of the cases, previously there were comments about it that it was too long. I believe before I used "Maintenance Mode: Enable" which gets quite long and take  lot of space. 

If anyone have any good suggestion what to do with the indicator, please let me know!

Lukas
