### ISSUE TITLE
Site stuck in Maintenance mode - cannot access wp-admin

### ISSUE THREAD

**Issue by Seajay1985** [lukasjuhas/lj-maintenance-mode#34]
I put my site into maintenance mode about a week ago. I was able to access wp-admin OK. 
NOW I am locked out by maintenance mode! wp-admin just gives me the maintenance mode screen. How do I get back in? Why has this happened? I've just been updating woocommerce products.
I have access to the site files and database OK. Please help. If all else fails I can restore a backup but I have done many updates during site maintenance and do not want to lose them.
Please Please help.
Thanks.

**Comment by lukasjuhas** [comment]
Thanks @Seajay1985 ! Just releasing hot fix.
