### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by lukasjuhas** [lukasjuhas/lj-maintenance-mode#4]
From Jack on WP Support forums:
"I've used the plugin and worked on my site for a day before I turned it off again. Now I notice almost 2000 not found url's and about 200 found server errors in Google Webmaster Tools. I've never had that before with other maintenance mode plugins. I love it by the way that it is so simple and light."

possible solution: nofollow meta tag

**Comment by jkomar** [comment]
This should be fixed by this pull request...

https://github.com/lukasjuhas/lj-maintenance-mode/pull/9

Jason
