### ISSUE TITLE
Add quick enable

### ISSUE THREAD

**Issue by lukasjuhas** [lukasjuhas/lj-maintenance-mode#42]
Perhaps via admin bar?

**Comment by morvy** [comment]
I think, that after configuring the plugin, it can stay in Settings > Maintenance Mode, while "Enabled/Disabled" toggle can do the switching (no need for submenu). To avoid accidental clicks, some devs put their maintenance mode info to the right side of the toolbar.

**Comment by lukasjuhas** [comment]
Hey @morvy,

I just had a think about this, I would prefer to leave it as it is for now. If I would change the link from settings page to actually enable disable the maintenance mode, I think that might cause some confusion so I've decided to leave it as it is for now, I'll perhaps think of a different way but for now it's gonna stay 

Cheers! Diky.

Lukas
