### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by lukasjuhas** [lukasjuhas/lj-maintenance-mode#6]
Considering switching wp_die() template to a custom one with bit of more flexibility. Would you prefer to keep plugin as it is or would you prefer to have a bit more flexibility, such as change background colour, change width etc. ?

Possible poll in the next update.

**Comment by jkomar** [comment]
I quite like it as it is using the wp_die() function. I just use inline styles for the styling on my maintenance page. The plugin is lightweight and free from bloat. Just the way it should be.

Jason

**Comment by lukasjuhas** [comment]
@jkomar Thank you Jason, 

Yeah, I'd like to keep it the way it is - it was pretty much built on that. I had few people requesting more flexibility but that can always be a separate plugin. Or "add-on" plugin. which would enable more features. Thank you for your feedback.

Lukas

**Comment by lukasjuhas** [comment]
I have decided to make an advanced mode of the plugin as add-on. Development is currently private with no due date.
